### ISSUE TITLE
React Warning for Mental Sums

### ISSUE THREAD

**Issue by afterdusk** [pinda-fun/pinda-fun#184]
When an input is accepted right before the game ends (<1s), the following warning appears on the console:
`
index.js:1375 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in MentalSumsGame (at MentalSums/index.tsx:43)
`

**Comment by indocomsoft** [comment]
![image](https://user-images.githubusercontent.com/11135744/68069520-e24d8480-fd9b-11e9-98bd-ba1c574d9b22.png)

The specific error.

![image](https://user-images.githubusercontent.com/11135744/68069524-eb3e5600-fd9b-11e9-93f4-018aae4bcadd.png)

The corresponding code.

There's a setTimeout. Need to clearTimeout
